Repository WildCodeSchool/2022-09-RMT-JSCREW-Externatic, pull requests merged in 2023-01, with the labels that each got.

#35 modification taille de la video en mode desktop
  frontend/src/pages/Home.jsx
Labels: Review Done

#34 Offre form
  backend/src/controllers/offreControllers.js
  backend/src/models/OffreManager.js
  backend/src/router.js
  frontend/src/App.jsx
  frontend/src/pages/BackOffice/Offre.jsx
  frontend/src/services/apiConnexion.js
Labels: Review Done

#33 Profil complement (add confirmation email, add photo avatar and cv, CSS, add select in photo and cv, updated JOI)
  backend/src/service/candidat.js
  frontend/src/assets/Avatar.png
  frontend/src/assets/cv.png
  frontend/src/pages/Profil/Profil.css
  frontend/src/pages/Profil/Profil.jsx
Labels: Change Requested, Review Done

#38 création du formulaire offre BackOffice
  backend/src/controllers/offreControllers.js
Labels: Review Done

#40 update burger menu for hidden scrollbar x
  frontend/src/components/NavBar/NavBar.css
Labels: Review Done

#41 Fix navbar
  frontend/src/components/NavBar/NavBar.jsx
Labels: Review Done

#39 Toastify offre form
  frontend/src/pages/BackOffice/Offre.jsx
Labels: Review Done

#42 mise en place d'une modale de connexion et un bouton d'accès depuis l…
  frontend/src/components/NavBar/NavBar.jsx
  frontend/src/components/UI/ConnexionModal.jsx
Labels: Change Requested, Review Done

#46 ajout navigation de la page home vers la page nosOffres
  frontend/src/pages/Home.jsx
Labels: Review Done

#49 Nav backoffice
  frontend/src/App.jsx
  frontend/src/components/UI/CardStats.jsx
  frontend/src/components/UI/EntrepriseForm.jsx
  frontend/src/components/UI/Sidebar.jsx
  frontend/src/pages/BackOffice/AdminEntreprise.jsx
  frontend/src/pages/BackOffice/Entreprise.jsx
  frontend/src/pages/Layout/Private.jsx
  frontend/src/pages/Layout/Public.jsx
  frontend/src/services/apiConnexion.js
Labels: Review Done

#48 Auth setup
  backend/database.sql
  backend/package.json
  backend/src/controllers/connexionControllers.js
  backend/src/middleware/auth.js
  backend/src/models/ConnexionManager.js
  backend/src/router.js
  backend/src/service/auth.js
  backend/src/service/connexion.js
Labels: Change Requested

#50 Complement upload profil le candidat peut mettre ou non une photo ou un cv
  backend/public/assets/avatar/Avatar.png
  backend/public/assets/cv/cv.png
  backend/src/controllers/candidatControllers.js
Labels: Change Requested, Review Done

#54 ajout de l'import des images dans la page qui.jsx
  frontend/src/pages/quisommesnous/qui.jsx
Labels: Review Done

#55 Reverse burger menu according to customer request , add connection button, hidding menu after clic
  frontend/src/components/NavBar/NavBar.css
  frontend/src/components/NavBar/NavBar.jsx
Labels: Review Done

#57 ajout data dans la table entrerprise pour le carousel
  backend/database.sql
Labels: Review Done

#59 Preview photo and cv in profil
  frontend/src/assets/cv_uploaded.png
  frontend/src/pages/Profil/Profil.jsx
Labels: Review Done

#62 correction findall dans le back + card cliquable de offres à offre
  backend/src/models/OffreManager.js
  frontend/src/pages/Offres/NosOffres.jsx
Labels: Review Done

#60 correction titre sur la page home
  frontend/src/pages/Home.jsx
Labels: Review Done

#63 Home carousel
  backend/src/controllers/entrepriseControllers.js
  backend/src/models/EntrepriseManager.js
  backend/src/router.js
  frontend/src/components/Carousel/Carousel.jsx
  frontend/src/pages/Home.jsx
Labels: Review Done

#56 creation de la table consultant et de ses données
  backend/database.sql
Labels: Review Done

#65 Pageoffre
  frontend/src/components/UI/Card.jsx
  frontend/src/components/UI/CardOffre/CarteAvantages.jsx
  frontend/src/components/UI/CardOffre/CartePrincipale.css
  frontend/src/components/UI/CardOffre/CartePrincipale.jsx
  frontend/src/components/UI/CardOffre/CarteProfil.jsx
  frontend/src/components/UI/CardOffre/CarteSalaire.jsx
  frontend/src/components/UI/CardOffre/ListOfOffers.jsx
  frontend/src/components/UI/ListOfOffers.jsx
  frontend/src/pages/Offres/NosOffres.jsx
  frontend/src/pages/UneOffre/UneOffre.jsx
Labels: Review Done

#66 Added get and update the profil
  backend/src/app.js
  backend/src/controllers/candidatControllers.js
  backend/src/controllers/connexionControllers.js
  backend/src/middleware/auth.js
  backend/src/models/CandidatManager.js
  backend/src/router.js
  backend/src/service/candidat.js
  frontend/.eslintrc.json
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/components/NavBar/NavBar.jsx
  frontend/src/components/UI/ConnexionModal.jsx
  frontend/src/components/UI/RegisterModal.jsx
  frontend/src/contexts/User.jsx
  frontend/src/main.jsx
  frontend/src/pages/Profil/Profil.jsx
  frontend/src/services/apiConnexion.js
Labels: Review Done

#69 Designnavbar
  backend/src/models/OffreManager.js
  frontend/src/components/NavBar/NavBar.css
  frontend/src/components/NavBar/NavBar.jsx
Labels: Review Done

#70 fix de la page home
  frontend/src/pages/Home.jsx
Labels: Review Done

#71 updated css in profil page
  frontend/src/pages/Profil/Profil.css
  frontend/src/pages/Profil/Profil.jsx
Labels: Review Done

#72 hotfix rajout demande client du mot menu
  frontend/src/components/NavBar/NavBar.jsx
Labels: Review Done

#74 changement password des 3 premiers candidats
  backend/database.sql
Labels: Review Done

#75 Candidature in profile
  backend/src/controllers/offreControllers.js
  backend/src/models/OffreManager.js
  backend/src/router.js
  frontend/src/components/UI/Card.jsx
  frontend/src/pages/Home.jsx
  frontend/src/pages/Profil/Profil.jsx
Labels: Review Done

#77 hotfix margin x navbar
  frontend/src/components/NavBar/NavBar.jsx
Labels: Review Done

#80 fix pour l'affichage des candidatures dans le profil
  frontend/src/components/UI/Card.jsx
  frontend/src/pages/Profil/Profil.jsx
Labels: Review Done

#68 Entreprise admin
  backend/src/controllers/domaineControllers.js
  backend/src/controllers/entrepriseControllers.js
  backend/src/models/DomaineManager.js
  backend/src/models/EntrepriseManager.js
  backend/src/router.js
  backend/src/service/entreprise.js
  frontend/src/components/UI/EntrepriseForm.jsx
  frontend/src/components/UI/EntrepriseSelect.jsx
  frontend/src/components/UI/Sidebar.css
  frontend/src/components/UI/Sidebar.jsx
  frontend/tailwind.config.js
Labels: Review Done

#78 mise en place SIO sur les pages accessibles au candidats
  frontend/index.html
  frontend/package.json
  frontend/public/externatic_favicon.png
  frontend/src/assets/externatic_favicon.png
  frontend/src/pages/Home.jsx
  frontend/src/pages/Offres/NosOffres.jsx
  frontend/src/pages/Profil/Profil.jsx
  frontend/src/pages/UneOffre/UneOffre.jsx
  frontend/src/pages/quisommesnous/qui.jsx
Labels: Review Done

#79 corrections liens dans le dashboard
  frontend/src/App.jsx
  frontend/src/components/UI/Sidebar.jsx
Labels: Review Done

#83 browsing and securing session and profile
  backend/database.sql
  backend/src/controllers/candidatControllers.js
  backend/src/models/CandidatManager.js
  backend/src/models/ConnexionManager.js
  frontend/src/components/NavBar/NavBar.jsx
  frontend/src/components/UI/ConnexionModal.jsx
  frontend/src/components/UI/RegisterModal.jsx
  frontend/src/contexts/User.jsx
  frontend/src/pages/Profil/Profil.jsx
Labels: Change Requested, Review Done

#84 Added disconnect button
  frontend/src/components/NavBar/NavBar.jsx
  frontend/src/contexts/User.jsx
Labels: Review Done

#90 Dashboard charts
  backend/src/controllers/candidatControllers.js
  backend/src/controllers/entrepriseControllers.js
  backend/src/controllers/offreControllers.js
  backend/src/models/CandidatManager.js
  backend/src/models/EntrepriseManager.js
  backend/src/models/OffreManager.js
  backend/src/router.js
  frontend/src/components/UI/CardStats.jsx
  frontend/src/components/UI/Sidebar.jsx
Labels: Review Done

#92 modifications emplacements boutons valider et retour
  frontend/src/components/UI/RegisterModal.jsx
Labels: Review Done

#89 creation composant candidatureTable, import du composant dans la page…
  backend/database.sql
  backend/src/controllers/candidaturesControllers.js
  backend/src/models/OffreManager.js
  backend/src/models/candidaturesManager.js
  backend/src/router.js
  frontend/src/components/Table/CandidatureTable.jsx
  frontend/src/pages/Profil/Profil.jsx
Labels: Review Done

#88 Added confirmation email after registration
  backend/package.json
  backend/public/assets/images/Logo-Externatic.png
  backend/src/controllers/candidatControllers.js
  backend/src/controllers/emailControllers.js
  backend/src/controllers/itemControllers.js
  backend/src/router.js
  frontend/src/pages/Profil/Profil.jsx
Labels: Review Done

#93 fix form offre et controler offre
  backend/src/controllers/offreControllers.js
  frontend/src/components/UI/OffreForm.jsx
Labels: Review Done

#95 fix page profil pour eslint
  frontend/src/pages/Profil/Profil.jsx
Labels: Review Done

#91 fix texte d'un input et changement de la taille du texte d'un bouton
  frontend/src/components/UI/RegisterModal.jsx
Labels: Review Done

#96 fix de la database
  backend/database.sql
Labels: Review Done

#97 changement de couleur dans le tableau
  frontend/src/components/Table/CandidatureTable.jsx
Labels: Review Done

#98 modification boutons des modales
  frontend/src/components/UI/ConnexionModal.jsx
  frontend/src/components/UI/RegisterModal.jsx
Labels: Review Done

#100 Filterby
  backend/database.sql
  backend/src/controllers/offreControllers.js
  backend/src/models/OffreManager.js
  backend/src/router.js
  frontend/src/assets/localisation.png
  frontend/src/assets/loupe.png
  frontend/src/components/UI/Card.jsx
  frontend/src/components/UI/CardOffre/CartePrincipale.jsx
  frontend/src/components/UI/Offres/FilterJob.jsx
  frontend/src/components/UI/Offres/FilterLocalisation.jsx
  frontend/src/components/UI/Offres/Pagination.css
  frontend/src/components/UI/Offres/Pagination.jsx
  frontend/src/pages/AllJobs.jsx
  frontend/src/pages/Offres/NosOffres.jsx
  frontend/src/pages/UneOffre/UneOffre.jsx
Labels: Review Done

#101 Candidatures in dashboard
  backend/database.sql
  backend/src/controllers/candidaturesControllers.js
  backend/src/models/candidaturesManager.js
  backend/src/router.js
  frontend/src/App.jsx
  frontend/src/components/UI/Sidebar.jsx
  frontend/src/pages/BackOffice/ConsultantDashboard.jsx
Labels: Review Done

#102 creation des consultants dans la page quisommesnous
  backend/database.sql
  backend/src/controllers/consultantsControllers.js
  backend/src/models/ConsultantsManager.js
  backend/src/router.js
  frontend/src/components/UI/CardConsultants.jsx
  frontend/src/pages/quisommesnous/qui.css
  frontend/src/pages/quisommesnous/qui.jsx
Labels: Review Done

#104 Hotfixdesign
  frontend/src/assets/recruitment2.gif
  frontend/src/components/Carousel/Carousel.jsx
  frontend/src/components/Footer/footer.jsx
  frontend/src/components/UI/Card.jsx
  frontend/src/components/UI/CardConsultants.jsx
  frontend/src/components/UI/Offres/FilterJob.jsx
  frontend/src/components/UI/Offres/FilterLocalisation.jsx
  frontend/src/pages/Home.jsx
  frontend/src/pages/UneOffre/UneOffre.jsx
  frontend/src/pages/quisommesnous/qui.jsx
Labels: Review Done

#107 hotfix du bouton connexion
  frontend/src/components/NavBar/NavBar.jsx
  frontend/src/components/UI/ConnexionModal.jsx
  frontend/src/components/UI/RegisterModal.jsx
Labels: Review Done

#106 déplacement mailoptions dans controllers pour réutiliser le service mail
  backend/src/controllers/candidatControllers.js
  backend/src/controllers/emailControllers.js
Labels: Review Done
